services:
  pg:
    image: postgres:17.5
    environment:
      POSTGRES_DB: film-library
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: