"""change sites table

Revision ID: ea414e11a4bc
Revises: 94046d42eaef
Create Date: 2025-07-29 01:52:29.140250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea414e11a4bc'
down_revision: Union[str, Sequence[str], None] = '94046d42eaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('site', sa.String(), nullable=False))
    op.drop_constraint(op.f('sites_movie_id_key'), 'sites', type_='unique')
    op.drop_column('sites', 'sites')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('sites', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('sites_movie_id_key'), 'sites', ['movie_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sites', 'site')
    # ### end Alembic commands ###
