"""change movie table

Revision ID: b22a973b71f4
Revises: 2a18889aaeee
Create Date: 2025-07-25 21:48:13.135732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22a973b71f4'
down_revision: Union[str, Sequence[str], None] = '2a18889aaeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('movies', 'origin_title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'movies', ['origin_title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.alter_column('movies', 'origin_title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('movies', 'image')
    # ### end Alembic commands ###
